### ISSUE TITLE
[PROPOSAL] - Regular Comms on TBD Ecosystem Development & News

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/open-source-programs#44]
**Desired outcome**
A regular, published series on what's new and evolving in the TBD ecosystem. Ideally leads to increased visibility into our efforts, heightened awareness, project usage, and contribution.

**Current Gaps**
We're not currently posting news on a timeboxed schedule, and community responds to consistent messaging through predictable cadence and comms channels.

**Implementation Suggestions (optional)** 
To be raised in Forum post and coordinated with Developer Relations, Open Source Engineering, and the community.

**Forum Discussion (optional)** 
TBD

**Discord Discussion (optional)** 
N/A

**Comment by ALRubinger** [comment]
On the benefits of a public change log:

https://twitter.com/gergelyorosz/status/1592447530201395200?s=46&t=xNsP-Npybmlbw57jpO_p9A

**Comment by ALRubinger** [comment]
Starting w/ Milestone 2:

* Communicate intended goals ASAP
* Set up template for Milestone completion for all to contribute to over the course of the Milestone
** Blog (@angiejones wanna DRI this?)
** High-level description of what's newly-available 
** Full release notes of each component (for project leads to contribute to)
** Comms strategy
*** Dev Twitter Account
*** Discord Message

@frankhinek what else?

**Comment by ALRubinger** [comment]
Input open here through COB Thursday when I'll start collating ideas and assembling the tooling and process for this.

**Comment by frankhinek** [comment]
It would be ideal to communicate the plans for the next milestone and a tentative preview for the one after that around the time we announce Milestone completion

**Comment by ALRubinger** [comment]
Handled through DevRel and @taniashiba - excellent
