### ISSUE TITLE
[PROPOSAL] - Open Source Events Calendar

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/open-source-programs#46]
**Events Calendar** 

_Desired outcome_
Simple way to add and view events. Open to contributors, or at least contributors with some level of trust. Best would be if there was one datastore for us to add/manage events in an open way, and we had tooling to surface these in a variety of mediums: Discord (like, "hey", event is starting at *link* in 5 minutes!), iCal/Google Calendar, developer.tbd.website. 

_Current Gaps_
Right now the only notion of "Events" we have is on [developer.tbd.website/events](https://developer.tbd.website/events), where the Markdown and images there are the single source of truth (datastore). This is probably fine for marquee events, but likely isn't the best place to keep routine meetings (for instance daily open source office hours on Discord voice channels, Twitter Spaces, ideas from core devs or the community, etc).

_Implementation Suggestions_
From `gleb#9120` on Discord:

> You can use the events feature that Discord has, this is a video showing how to easily set it up: https://www.youtube.com/watch?v=Bi6ScSfWruk

> You can also use a bot to link a google calendar to your discord events the link for that is here: https://top.gg/bot/903380664336928798

_Discord Discussion (optional)_
https://discord.com/channels/937858703112155166/937858703820980296/1070482398799724617

**Comment by ALRubinger** [comment]
Contributors - what ideas you got?

**Comment by chaadayev** [comment]
What you could do is set up a public google calendar that you link to your discord events using the ChronicleBot. You could then either allow the public to edit the calendar however this has a high likelihood of getting abused so another option would be to have an extra discord channel or google form for event requests that would then be checked by a member of the team and consequently have relevant events added to the public google calendar.

**Comment by ALRubinger** [comment]
Awesome! Leaving this open as a proposal for awhile to collect ideas.

**Comment by ALRubinger** [comment]
Hooked together as recommended by @chaadayev - trial prototyping now:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/199891/217961952-a75a9cba-00ed-462a-be5e-af287d8de096.png">

**Comment by angiejones** [comment]
> What you could do is set up a public google calendar that you link to your discord events using the ChronicleBot. You could then either allow the public to edit the calendar however this has a high likelihood of getting abused so another option would be to have an extra discord channel or google form for event requests that would then be checked by a member of the team and consequently have relevant events added to the public google calendarndar.


> What you could do is set up a public google calendar that you link to your discord events using the ChronicleBot. You could then either allow the public to edit the calendar however this has a high likelihood of getting abused so another option would be to have an extra discord channel or google form for event requests that would then be checked by a member of the team and consequently have relevant events added to the public google calendar.

agree with this. preference towards google form so that it's not biased towards developers (who tend to be the audience most comfortable in our Discord).

**Comment by ALRubinger** [comment]
> agree with this. preference towards google form so that it's not biased towards developers (who tend to be the audience most comfortable in our Discord).

OK awesome, so the TODO I see for this issue is set up a GH issue template for folks to request a new Calendar event - proposing this instead of a Google form for consistency in how the public asks things of the team.  Makes sense @angiejones?

**Comment by ALRubinger** [comment]
Another task to do when closing this is to make an issue on developer.tbd.website for a page showing how to add the Calendar to Google Calendar [via this link](https://calendar.google.com/calendar/u/0?cid=Y19iMmI4MzY3ZGFjNTM2ZWJmNzU3YjI3NDVmY2M1ZmJmZjIwOTlmNmM1NzRiYzEzZjgzZDE2NDIzZGIyZGQ1NTM1QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

**Comment by taniashiba** [comment]
Proposal / feedback @ALRubinger -

1. Add a single-sentence summary of what will be discussed / what the goal of the event is. Then add whether or not you are required to participate, if so how. Rough example: "developer.tbd.website Daily Sync recurs daily. Listen to what the team's up to and ask questions 1-1 in the last 5 minutes."
2. Add calendar to welcome channel / message new members see upon joining Discord. This one is pretty straight-forward, but adding anyway!
2. Next level: Add an !events or similar command to pull up recurring + one-off events in Discord, can potentially work with ChronicleBot. This way whenever someone asks about events or wants to know what's going on, they know how to pull up events.

Hope this helps! :)

**Comment by ALRubinger** [comment]
Appreciated @taniashiba!

AI for me: decompose into tasks for the developer.tbd.website project board. Link to here so @taniashiba and the rest of the community gets good tracking. To incorporate into the current Phase 2 work.

**Comment by ALRubinger** [comment]
@dayhaysoos One thing to walk through here will be how we differentiate the meetings on Discord from events @angiejones is currently maintaining in Markdown on the site repo itself. For instance, can Google Calendar become the data store for our events? If so, what would the new [events page on developer.tbd.website](https://developer.tbd.website/events) look like? Do we need to show upcoming meetings in a different way than Spaces, Workshops, Conferences, etc? Let's link w/ @angiejones on this before coming to decisions, but we can do some R&D and see what's involved if we were to hook the events page to be driven from the Google Calendar backend.

**Comment by Sydnee510** [comment]
So from my understanding, there needs to be a way to keep track and remind contributors about the daily meetings/spaces happening in discord and also do the same for upcoming workshops/spaces happening externally. 

I think that the events tab should have two different sections where users can see the list of daily/weekly events and then there should also be calendar invites attached. So they can either subscribe to the calendar for all meetings or they can subscribe to individual meetings. The other section would be a list of the external events/workshops/conferences and etc. that don't happen on discord. Users should also be able to subscribe to a calendar invite for these individual events as well. 

For one UI component there can be a visual calendar so users can see all the upcoming/recurring events happening on discord and externally. (The calendar can maybe sit at the top of the page above the list of events or it can sit below, whichever is more appealing to the eye.)

The discord bot reminders are also a great way to remind contributors about the events happening. The discord bot can give either 10-60min ahead to starting notifications to the server. Another idea would be to also send email reminders before the events/calls about 60min or so before the calls/events. The daily discord meetings could probably just utilize the discord bot and calendar invites. The external events/workshops could most benefit from those email reminders, calendar invites and also the discord bot reminders as well. Both of these reminders should happen automatically as folks have either subscribed to the calendar or are currently on discord.

**Comment by ALRubinger** [comment]
@ALRubinger to decompose into tasks and perhaps phases w/ @dayhaysoos

**Comment by ALRubinger** [comment]
AIs for @dayhaysoos:

- [ ] Create main issue in [developer.tbd.website](https://github.com/TBD54566975/developer.tbd.website) tracker for just the Calendar page
- [ ] Create sub-bullets in that issue, or new issues, consider decomposing this into its pieces or phases?
- [ ] Phase 1 - Embed Google Calendar into a "Meetings" section on "Events" page? Talk about this w/ @angiejones 
- [ ] Phase 2 - Ingest Google Calendar data and surface inlined into Meetings page?

**Comment by ALRubinger** [comment]
Done on https://developer.tbd.website/community
