### ISSUE TITLE
[INCUBATION PROGRAM REQUEST] - New Project: tbLEND

### ISSUE THREAD

**Issue by jondwest** [TBD54566975/open-source-programs#60]
### Introduction

Tell us about you, your organization, and your mission!
FormFree.com has a mature product, RIKI (Residual Income Knowledge Index). RIKI is a set of Ability to Pay (ATP) Indices that lenders can use to qualify borrowers for all sorts of loans (mortgage, auto, personal, etc.). Furthermore, RIKI also significantly targets the financially underserved. That is, consumers with FICO < 660 are left behind because lenders don't have the tools or time to qualify them. RIKI examines their ability to pay. The result is a likely population of 10.7 million people in the US who have low FICO, but would qualify for a mortgage. FormFree, Sophtron, and MX are instigating a tbDEX-like protocol called tbLEND. We want to serve the underserved, eliminate the circular and silly requirement to go into debt to qualify for debt, make debt based decision on ability to pay, and create an open competitive lending marketplace that has no rent-seekers.

### Proposal

Let's hear about your project; please describe your idea and its value to the TBD ecosystem.
The project is described in these recordings.
https://1drv.ms/f/s!Aq2zjTdx7n0XzEz4zjFDGqbOtM6C?e=uukLxI

### Existing repository

No

### User Flow

Paste relevant images or screenshots here
See recordings link in the Proposals section.

### Information Flow between Services

Paste relevant images or screenshots here
See recordings link in the Proposals section.

### Contributor License Agreement

Yes

**Comment by ALRubinger** [comment]
Thank you! Quick update some TBD folks will be meeting on this next week and I'll update then - accommodating some of our team's summer PTO.

**Comment by ALRubinger** [comment]
Thank you @jondwest!

Appreciate your writing this up and meeting with us! Some proposed next steps - WDYT?

**Proposed Action** 
* Welcome TBLend into Incubation Program
* Establish FormFree as sponsor
* Discuss new name
  * Justification: “TBL” isn’t “TBD”
  * Draw clear line between community effort and TBD the business

**Proposed Project Summary**
TBLend improves the vetting experience for the lending industry. It’s built as a protocol atop the Web5 Platform and take advantage of Web5 core tenets: decentralized identity, verifiable credentials, data self-ownership, and permissionless networking. Through these foundational concepts, TBLend is equipped to correct longstanding biases in lending; it incorporates a more comprehensive view of applicants’ financial health and ability to pay than status quo credit reporting systems.

TBLend strengthens the Web5 ecosystem by introducing a real-world use case for protocol development. We expect this will tighten the feedback loop for both Web5 and tbDEX development, allowing engineering groups of core techs like the Web5 API, SSI Suite, and Decentralized Web Nodes with FormFree as an institutional contributor and developer atop TBD projects.

**Action Plan**
* Review with FormFree and other proposers
* Establish monthly cadence for meeting with TBD sponsors (@ALRubinger, @csuwildcat, Ben, @frankhinek) to track project roadmap, identify issues, and proactively monitor FormFree’s needs to set them up for success
* Feature TBLend and FormFree on the [Incubation Program page](https://developer.tbd.website/open-source/incubation)
* Ongoing: Maintain project health or identify components that may be better served spun off into new projects or sunset as prototypes mature.

**Comment by jondwest** [comment]
Here is an updated Project Summary: 
<begin>
tbLEND is bringing Web5's network effects, competitive markets, and data sovereignty to the consumer lending industry. tbLEND is an open and permissionless protocol built atop the Web5 Platform. Early participants in tbLEND include MX.com, Sophtron.com, FormFree.com and others to-be-announced. tbLEND will improve consumer lending, beginning with the consumer's ability to find and vet loan offers, improve lenders' qualified borrower leads, improve the market place for loan application data that lender's need to gather, and help loan application data providers (VC providers) to better monetize their services. All three participant types will receive more volume and higher quality services at more competitive prices due to Web5's ability to mimic a completely open and competitive market place... all with data sovereignty.

tbLEND will also correct long standing biases in lending, and improve financial inclusion and financial literacy. It does so via VCs that indicate loan applicants’ ability to pay (ATP) indices in place of status quo credit reporting systems. There are 16.7M Americans who can provably service a loan, but are excluded based on credit scores. In addition, ATP helps consumers know and monitor their financial health.

Finally, tbLEND strengthens the Web5 ecosystem by introducing a real-world use case for protocol development. We expect this will tighten the feedback loop for both Web5 and tbDEX development, allowing Web5 FOSS engineering groups to benefit from the contributions of tbLEND participants.
<end>

My guess is that we want to establish FormFree, Sophtron, and MX as sponsors of the Incubation Project? Can/should there be only one sponsor? I'm fine with FormFree being the sole sponsor, but I also invite multiple sponsors in the spirit of FOSS and multiple participants.

Will there a press release similar to the VCS press release?
https://developer.tbd.website/blog/announcing-web5-verifiable-credential-selector/

Yes, we can discuss a new name, but would like to understand how tbLEND is different than tbDEX.

**Comment by smartsicity** [comment]
This is great work! Love it! We build decentralized, smart microcities (actual physical sites that will be using strictly DEFI, blockchain, AI and sustainable building/3d printing/pre-fab with circular energy systems from BTC miners and UHPC data centers waste heat to power everything and everyone. We will be contributing everything we create, and hope to also implement many of the incredible things everyone is working on here, including your lending! This is great. We look forward to seeing more and sending in our stuff!

**Comment by ALRubinger** [comment]
Approved and active.
