### ISSUE TITLE
Lock Dependency Versions

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/open-source-programs#84]
All dependencies should be explicitly set; no version ranges. Locked versions reduce several security risks:

* They ensure that checking and deployment are all done with the same software, reducing deployment risks, simplifying debugging, and enabling reproducibility.
* They can help mitigate compromised dependencies from undermining the security of the project (in the case where you've evaluated the pinned dependency, you are confident it's not compromised, and a later version is released that is compromised).
* They are one way to counter dependency confusion (aka substitution) attacks, in which an application uses multiple feeds to acquire software packages (a "hybrid configuration"), and attackers fool the user into using a malicious package via a feed that was not expected for that package.

It comes with the tradeoff of inhibiting dependency updates for a vulnerability fix. To mitigate this we need to use automated tools that detect such VULNs and also notify about outdated dependencies.

Reference: https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

**Comment by ALRubinger** [comment]
@andresuribe87 May I add your comments in the Google Doc here? It was a good discussion about what versions we should lock (ie. Plugins, Test Deps, etc?) I'd like to reflect here as we port the work into GH Issues

**Comment by andresuribe87** [comment]
@ALRubinger of course! Got nothing to hide :)

**Comment by ALRubinger** [comment]
Done for now, adding issue for automation to protect against this going forward: #142
