### ISSUE TITLE
Enable FOSSA Public View

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/open-source-programs#90]
Enable a public, read-only view of FOSSA results.

**Comment by ALRubinger** [comment]
@leordev do you remember the status of this? Available as a feature now, or coming soon?

**Comment by leordev** [comment]
It is available, FOSSA allow us to make the project public! I'm doing it for all of our CI pilots. Will update here as soon as I have all of them working!

**Comment by ALRubinger** [comment]
Awesome @leordev and if you have issues in the projects you're putting those in, can link here as dependent tasks in the summary so you don't need to return to do updates!

**Comment by ALRubinger** [comment]
Done.
