### ISSUE TITLE
Enable Synk Public View

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/open-source-programs#91]
Document this URL in Notion when done.

**Comment by ALRubinger** [comment]
@leordev Do you remember the status of this? Available as a feature soon, or no?

**Comment by leordev** [comment]
Not sure if we can expose Snyk, but since we are publishing via SARIF to Github Security, we might!

**Comment by ALRubinger** [comment]
@leordev Oh SARIF to GH Security works fine too I think too - because it'll surface as a public report, yeah?

**Comment by ALRubinger** [comment]
No more Snyk
